---
language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - docker build -t "codeclimate:build" .
  - ~/official-images/test/run.sh "codeclimate:build"

after_script:
  - docker images
